# Generated by Django 4.1.3 on 2022-12-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField()),
                ('Aadhar', models.IntegerField(blank=True, null=True)),
                ('Pan', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=40, null=True)),
                ('Ac_No', models.IntegerField(blank=True, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Month', models.DateField(blank=True, null=True)),
                ('Share_Money', models.IntegerField(blank=True, null=True)),
                ('Late_Charge', models.IntegerField(blank=True, null=True)),
                ('Balance', models.IntegerField(blank=True, null=True)),
                ('Loan', models.IntegerField(blank=True, null=True)),
                ('Loan_Installment', models.IntegerField(blank=True, null=True)),
                ('Loan_Interest', models.IntegerField(blank=True, null=True)),
                ('Late_Loan_Charge', models.IntegerField(blank=True, null=True)),
                ('Loan_Balance', models.IntegerField(blank=True, null=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
