# Generated by Django 4.1.3 on 2022-12-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
