# Generated by Django 4.1.3 on 2023-01-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0002_alter_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='IFSC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userBankAccount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userBankName',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
