# Generated by Django 4.1.3 on 2023-01-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0003_userdetails_ifsc_userdetails_userbankaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='userBankAccount',
            new_name='Holder_Account_number',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='userBankName',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Holder_Bank_Name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
