# Generated by Django 4.1.3 on 2023-01-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0004_rename_userbankaccount_userdetails_holder_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
