# Generated by Django 4.1.3 on 2023-01-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0005_userdetails_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='Holder_Account_number',
            new_name='Account_number',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='Holder_Bank_Name',
            new_name='Bank_Name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
    ]
