# Generated by Django 3.2.9 on 2023-03-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0009_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
