# Generated by Django 3.2.9 on 2023-03-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0010_alter_userdetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Bank_Name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='IFSC',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
