# Generated by Django 3.2.9 on 2023-03-30 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KalyanFinalCutApp', '0012_auto_20230330_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Membership_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
