# Generated by Django 3.2.9 on 2023-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0014_alter_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
