# Generated by Django 3.2.9 on 2023-04-01 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KalyanFinalCutApp', '0016_auto_20230402_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='IFSC',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reference', to=settings.AUTH_USER_MODEL),
        ),
    ]
