# Generated by Django 3.2.9 on 2023-04-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0017_auto_20230402_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Aadhar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
