# Generated by Django 3.2.9 on 2023-04-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0018_alter_userdetails_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
