# Generated by Django 3.2.9 on 2023-04-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0019_alter_userdetails_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='gender',
            field=models.PositiveBigIntegerField(choices=[(1, 'male'), (2, 'female')], default=1),
            preserve_default=False,
        ),
    ]
