# Generated by Django 3.2.9 on 2023-04-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0020_auto_20230402_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
