# Generated by Django 3.2.9 on 2023-04-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0024_auto_20230408_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='S_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='Month',
            field=models.DateField(auto_now_add=True),
        ),
    ]
