# Generated by Django 3.2.9 on 2023-04-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0029_auto_20230409_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.AutoField(default='01', primary_key=True, serialize=False),
        ),
    ]
