# Generated by Django 3.2.9 on 2023-04-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0031_auto_20230409_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='nominee1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='nominee2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
