# Generated by Django 3.2.9 on 2023-04-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0032_auto_20230411_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Date_of_birth_nominee1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Date_of_birth_nominee2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='relation_with_nominee1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='relation_with_nominee2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
