# Generated by Django 3.2.9 on 2023-04-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0033_auto_20230411_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
