# Generated by Django 3.2.9 on 2023-04-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0034_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Date',
        ),
        migrations.AlterField(
            model_name='payment',
            name='Month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
