# Generated by Django 3.2.9 on 2023-08-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0035_auto_20230416_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Share_Money',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Pan',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
