# Generated by Django 3.2.9 on 2023-08-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KalyanFinalCutApp', '0036_auto_20230820_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
