# Generated by Django 3.2.7 on 2023-11-14 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KalyanFinalCutApp', '0038_auto_20231022_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('Ac_No', models.IntegerField(blank=True, default=0, null=True)),
                ('loan_date', models.DateField(blank=True, null=True)),
                ('loan_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('loan_intrest_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('loan_principle', models.IntegerField(blank=True, default=0, null=True)),
                ('loan_intrest_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
